Repository vigneshs-dev/Q-Vote, pull requests merged in 2024-10, with the labels that each got.

#11 feat/9: Dockerise application
  .dockerignore
  Dockerfile
  README.md
  src/app.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 [Feature Request]: DarkMode Toggle #6
  .gitignore
  src/templates/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 added error messages to login page
  src/app.py
  src/static/style.css
  src/templates/login.html
  src/votes.db
Labels: bug, hacktoberfest, hacktoberfest-accepted

#29 Improve register page error handling
  src/app.py
  src/static/style.css
  src/templates/login.html
  src/templates/register.html
Labels: bug, hacktoberfest, hacktoberfest-accepted

#33 Hide the separate votes count
  src/app.py
  src/static/style.css
  src/templates/vote.html
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#34 Added Darkmode
  src/static/darkmode.js
  src/static/style.css
  src/templates/index.html
  src/templates/login.html
  src/templates/register.html
  src/templates/results.html
  src/templates/vote.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#35 Login and signup pages are workin
  src/db/votes.db
  src/static/login.css
  src/static/register.css
  src/static/style.css
  src/templates/login.html
  src/templates/register.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#38 Update UI of the Voting and Results page
  package-lock.json
  src/db/votes.db
  src/static/login.css
  src/static/results.css
  src/static/vote.css
  src/templates/results.html
  src/templates/vote.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
